using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Welcome.Model;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Welcome.Others;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Welcome.ViewModel;

//namespace Welcome.Model

namespace DataLayer.Model
{
    public class DatabaseUser : User
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)] // the values for the Id will be generated by the database. 
        public override int Id { get; set; }
        //public DatabaseUser(string name, string password, UserRolesEnum role, string facNum, string email, DateTime expireDate) : base(name, password, role, facNum, email)
        //{
        //}
    }
}
